### PR TITLE
build outline of Gallery Page #80

### LINKED ISSUE #80: build outline of Gallery Page
build out the gallery page main components, don't add any images or anything along that way just add the background components then we will add the content to the page in later issues, use the design Monica made for us

### PR DESCRIPTION
**Pull request by mbndvmDevslopes**

### CODE REVIEW

**Review by Iconians — CHANGES_REQUESTED** [review]
this is a great start but could you make the header part similar to whats in the design

**Comment by mbndvmDevslopes** [comment]
When I try to push I get this error: "fatal: The current branch 80-build-outline-of-gallery-page has multiple upstream branches, refusing to push.".  I am uncertain how to resolve despite researching for quite a while.  Any suggestions?

**Comment by Iconians** [comment]
this is what chatgpt gave me when I asked about your error. Have you ran through these steps already if so let me know and I'll do some deeper research 
This error occurs when Git detects that the current branch has multiple upstream branches, and it is not clear which one should be used for pushing changes. To resolve this issue, you need to specify the branch you want to push explicitly.

Here are a few steps to help you resolve this:

Check the Current Branch:
Ensure you are on the correct branch where you want to push changes. You can use the following command to check the current branch:

bash
Copy code
git branch
Check Remote Branches:
List the remote branches to see which ones are associated with the current branch:

bash
Copy code
git branch -r
Specify the Remote and Branch Name:
Explicitly specify the remote and branch name when pushing:

bash
Copy code
git push <remote-name> <branch-name>
For example, if your remote is named origin and you are on branch 80-build-outline-of-gallery-page, you can run:

bash
Copy code
git push origin 80-build-outline-of-gallery-page
Replace origin with the actual name of your remote if it's different.

Update the Upstream Branch:
If you want to set the upstream branch for your local branch, you can use the following command:

bash
Copy code
git branch --set-upstream-to=<remote-name>/<branch-name>
For example:

bash
Copy code
git branch --set-upstream-to=origin/80-build-outline-of-gallery-page
This associates your local branch with the specified remote branch.

After following these steps, you should be able to push changes without encountering the error. If you still face issues, double-check your Git configuration and verify that the branch and remote settings are correct.

**Comment by mbndvmDevslopes** [comment]
Still trying to figure it out but haven't yet been successful and am open to suggestions.  I tried the above suggestions without avail.

**Pull request closed without merging**
