### PR TITLE
add upcoming event section

### LINKED ISSUE #8: upcoming/current events - yellow
this section will go under the intro text section 

copy from client

Upcoming Events
--
Giving Tuesday, November 28, 2023
Participate in Giving Tuesday by supporting Way to Health, enabling us to sustain crucial care for the underprivileged. A mere $1 can furnish medicine for a malnourished baby, potentially saving their life. Your contribution makes a significant impact on those in need.
 
Expansion of the Malnourished Baby Feeding Initiative
As we conclude 2023, unite with us to broaden our feeding initiative. We aim to extend the feeding program from 34 malnourished babies to 90, reaching more communities by expanding into additional neighborhoods in Cite Soleil, Haiti. (Add in a LEARN MORE link that goes into the "Our Work" datapage)

### PR DESCRIPTION
**Pull request by Coderuff919**
Add Upcoming Event Section

### CODE REVIEW

**Comment by Iconians** [comment]
Hey Monica did you do a git pull before opening the pull request since I'm seeing the main_sub section in your branch which was deleted and I know Zach and Eric had branches merged into main since that section was removed, could you do the git pull then ask for the pr again, besides that, what you did looks great

**Comment by Coderuff919** [comment]
Hey Clayton, yes I did. Everything was up to date at that point but I will do the got pull again later. How do you resubmit a new PR if you still have an open PR? Just do the same steps as usual?

**Comment by Iconians** [comment]
Hi Monica it looks like we won't need to open a new PR but if you do the git pull on the main branch it should pull all the changes to your local branch then update the sections of 8-upcomingcurrent-events-yellow branch where there's differences which I don't thinks there's much

**Comment by Rahnken** [comment]
You could also do a new PR, where you switch the branches so you are merging main into the feature branch, this sometimes is an easier process if you've made significant changes on your feature branch after creating the branch from an earlier main state

**Comment by Coderuff919** [comment]
Thanks for the tip Clayton & Eric, I just did a git pull and everything is up to date, can you check please @Iconians

**Comment by Iconians** [comment]
I am still seeing the main_sub section on github in your branch did you update main then change the branch you worked on or do like eric mentioned and make a new pr on a different branch? here is a pic of what I am seeing in the 8-upcomingcurrent-events-yellow
image of what I am seeing on github

**Comment by Iconians** [comment]
if you want we could jump in the general chat and see about seeing how to resolve this, I just looked at Matt's PR and he has a similar issue as well

**Pull request merged**
